services:
  core_prod_api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: core_prod_api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - './logs/:/app/logs/'
    networks:
      - core_prod_network
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '5'

networks:
  core_prod_network:
    name: core_prod_network
    external: true
