services:
  # API Service
  local_core_api:
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile
    container_name: local_core_api
    restart: on-failure
    env_file:
      - .env
    ports:
      - '${APP_PORT}:${APP_PORT}'
    depends_on:
      - local_core_db
      - local_core_rabbitmq
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - local_core_network
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '5'

  # PostgreSQL Service
  local_core_db:
    image: postgres:15.12-alpine3.21
    container_name: local_core_db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=99Xe4MyS4Cf6Dzt
      - POSTGRES_DB=db_boiler
    ports:
      - '5880:5432'
    volumes:
      - local_core_db_data:/var/lib/postgresql/data
    networks:
      - local_core_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME} -p ${DB_PASS}']
      interval: 10s
      timeout: 5s
      retries: 3

  # RabbitMQ
  local_core_rabbitmq:
    image: rabbitmq:3.13.7-management-alpine
    container_name: local_core_rabbitmq
    restart: always
    ports:
      - '5677:${RABBITMQ_PORT}'
      - '15677:15672'
    env_file:
      - .env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    networks:
      - local_core_network

volumes:
  local_core_db_data:

networks:
  local_core_network:
    name: local_core_network
    driver: bridge
